export type DepartmentCategory =
  | 'leadership'
  | 'web-dev'
  | 'seo-analytics'
  | 'branding-identity'
  | 'creative-studio'
  | 'digital-marketing'
  | 'game-interactive'
  | 'academy-hub';

export interface DepartmentFilterInfo {
  key: DepartmentCategory;
  nameEn: string;
  nameFa: string;
}

export const DEPARTMENTS_LIST: DepartmentFilterInfo[] = [
  { key: 'leadership', nameEn: 'Co-Founders', nameFa: 'هم‌بنیان‌گذاران' },
  { key: 'web-dev', nameEn: 'Web & Dev', nameFa: 'وب و توسعه' },
  { key: 'seo-analytics', nameEn: 'SEO & Analytics', nameFa: 'سئو و تحلیل داده' },
  { key: 'branding-identity', nameEn: 'Branding & Identity', nameFa: 'برندینگ و هویت' },
  { key: 'creative-studio', nameEn: 'Creative Studio', nameFa: 'گرافیک و انیمیشن' },
  { key: 'digital-marketing', nameEn: 'Digital Marketing', nameFa: 'دیجیتال مارکتینگ' },
  { key: 'game-interactive', nameEn: 'Game & Interactive', nameFa: 'بازی‌سازی و تعاملی' },
  { key: 'academy-hub', nameEn: 'Academy & Learning', nameFa: 'آموزش و توسعه مهارت' },
];

export interface MemberData {
  id: string;
  code: string;
  nameEn: string;
  nameFa: string;
  roleEn: string;
  roleFa: string;
  badgeEn: string;
  badgeFa: string;
  isFounder: boolean;
  department: DepartmentCategory;
  image: string;
  bioEn: string;
  bioFa: string;
  stats: {
    labelEn: string;
    labelFa: string;
    val: string;
  }[];
  skillsEn: string[];
  skillsFa: string[];
  // Constellation coordinate percentages on 2D canvas (0 - 100)
  coord: { x: number; y: number };
  // Connection line peer IDs
  connectsWith: string[];
}

export const ALL_TEAM_MEMBERS: MemberData[] = [
  // 1. LEADERSHIP (3 EQUAL CO-FOUNDERS - EXACT SAME VALUE & STATURE)
  {
    id: 'abdollah',
    code: 'JRK-FND-01',
    nameEn: 'Abdollah',
    nameFa: 'عبدالله',
    roleEn: 'Co-Founder & Spatial Architect',
    roleFa: 'هم‌بنیان‌گذار و معمار فضا',
    badgeEn: 'CO-FOUNDER',
    badgeFa: 'هم‌بنیان‌گذار',
    isFounder: true,
    department: 'leadership',
    image: '/assets/images/team/abdollah.png',
    bioEn: 'Shaping spaces, systems, and multidisciplinary creative experiences with structural clarity and architectural balance.',
    bioFa: 'طراحی فضاها، سیستم‌های پیچیده چندرشته‌ای و هدایت ساختار دیزاین استودیو با رویکرد مهندسی و بصری یکپارچه.',
    stats: [
      { labelEn: 'Direction', labelFa: 'هدایت خلاق', val: 'Systemic' },
      { labelEn: 'Architecture', labelFa: 'معماری فضا', val: 'Spatial' },
      { labelEn: 'Co-Founder', labelFa: 'هم‌بنیان‌گذار', val: 'Equal Lead' },
    ],
    skillsEn: ['Spatial Architecture', 'Design Systems', 'Concept Modeling', 'Spatial Prototyping'],
    skillsFa: ['معماری فضا', 'دیزاین سیستم', 'مدل‌سازی مفهومی', 'پروتوتایپ معماری'],
    coord: { x: 34, y: 36 },
    connectsWith: ['rouhollah', 'sina', 'danial'],
  },
  {
    id: 'rouhollah',
    code: 'JRK-FND-02',
    nameEn: 'Rouhollah',
    nameFa: 'روح‌الله',
    roleEn: 'Co-Founder & Lead Tech Architect',
    roleFa: 'هم‌بنیان‌گذار و معمار فنی و وب سه‌بعدی',
    badgeEn: 'CO-FOUNDER',
    badgeFa: 'هم‌بنیان‌گذار',
    isFounder: true,
    department: 'leadership',
    image: '/assets/images/team/rouhollah.png',
    bioEn: 'Pioneering cutting-edge digital craftsmanship, software architecture, shaders, WebGL, and high-performance real-time systems.',
    bioFa: 'توسعه زیرساخت‌های مهندسی، برنامه‌نویسی خلاق، وب سه‌بعدی تعاملی، شیدرها و معماری پایدار نرم‌افزاری استودیو.',
    stats: [
      { labelEn: 'Engine', labelFa: 'موتور وب', val: 'WebGL 2.0' },
      { labelEn: 'Frame Rate', labelFa: 'روانی اجرا', val: '60 FPS' },
      { labelEn: 'Co-Founder', labelFa: 'هم‌بنیان‌گذار', val: 'Equal Lead' },
    ],
    skillsEn: ['WebGL & Three.js', 'React & Architecture', 'Performance Tuning', 'Interactive Shaders'],
    skillsFa: ['وب‌جی‌ال و Three.js', 'ری‌اکت و معماری کد', 'بهینه‌سازی پرفورمنس', 'شیدرهای تعاملی'],
    coord: { x: 66, y: 36 },
    connectsWith: ['abdollah', 'sina', 'maryam', 'behdad'],
  },
  {
    id: 'sina',
    code: 'JRK-FND-03',
    nameEn: 'Sina',
    nameFa: 'سینا',
    roleEn: 'Co-Founder & Brand Art Director',
    roleFa: 'هم‌بنیان‌گذار و مدیر آرت و هویت بصری',
    badgeEn: 'CO-FOUNDER',
    badgeFa: 'هم‌بنیان‌گذار',
    isFounder: true,
    department: 'leadership',
    image: '/assets/images/team/sina.png',
    bioEn: 'Crafting bespoke brand identities, tactile typography, expressive illustrations, and holistic visual narratives.',
    bioFa: 'خلق هویت‌های بصری ماندگار، تایپوگرافی مفهومی، تصویرسازی‌های متمایز و هدایت سبک هنری پروژه‌های استودیو.',
    stats: [
      { labelEn: 'Brand Craft', labelFa: 'ظرافت برند', val: 'Bespoke' },
      { labelEn: 'Typography', labelFa: 'تایپوگرافی', val: 'Custom' },
      { labelEn: 'Co-Founder', labelFa: 'هم‌بنیان‌گذار', val: 'Equal Lead' },
    ],
    skillsEn: ['Visual Identity', 'Typography Design', 'Tactile Motion', 'Art Direction'],
    skillsFa: ['هویت بصری', 'دیزاین تایپوگرافی', 'موشن لمسی', 'آرت‌دایرکشن'],
    coord: { x: 50, y: 56 },
    connectsWith: ['abdollah', 'rouhollah', 'parsa', 'nima'],
  },

  // 2. WEB & DEV
  {
    id: 'danial',
    code: 'JRK-WEB-01',
    nameEn: 'Danial',
    nameFa: 'دانیال',
    roleEn: 'Senior Frontend & WebGL Engineer',
    roleFa: 'توسعه‌دهنده ارشد فرانت‌اند و وب‌جی‌ال',
    badgeEn: 'SPECIALIST',
    badgeFa: 'متخصص فنی',
    isFounder: false,
    department: 'web-dev',
    image: '/assets/images/team/danial.jpg',
    bioEn: 'Engineering seamless interactive interfaces, micro-animations, GSAP timelines, and modular client architectures.',
    bioFa: 'پیاده‌سازی رابط‌های کاربری تعاملی، انیمیشن‌های روان وب، تایم‌لاین‌های GSAP و معماری ماژولار فرانت‌اند.',
    stats: [
      { labelEn: 'Animations', labelFa: 'میکرواینتراکشن', val: 'Fluid' },
      { labelEn: 'TypeScript', labelFa: 'تایپ‌استریکت', val: '100%' },
      { labelEn: 'Experience', labelFa: 'سابقه تخصصی', val: '6+ Yrs' },
    ],
    skillsEn: ['TypeScript', 'GSAP Animation', 'Tailwind & UI', 'Vite & Next.js'],
    skillsFa: ['تایپ‌اسکریپت', 'انیمیشن‌های GSAP', 'دیزاین مدرن UI', 'فریم‌ورک‌های وب'],
    coord: { x: 20, y: 28 },
    connectsWith: ['abdollah', 'maryam'],
  },
  {
    id: 'maryam',
    code: 'JRK-WEB-02',
    nameEn: 'Maryam',
    nameFa: 'مریم',
    roleEn: 'Backend & Cloud Infrastructure Architect',
    roleFa: 'مهندس زیرساخت ابری و معماری سرور',
    badgeEn: 'SPECIALIST',
    badgeFa: 'متخصص فنی',
    isFounder: false,
    department: 'web-dev',
    image: '/assets/images/team/maryam.jpg',
    bioEn: 'Designing resilient distributed backend microservices, real-time WebSockets, and low-latency cloud infrastructure.',
    bioFa: 'طراحی میکروسرویس‌های توزیع‌شده با قابلیت اطمینان بالا، وب‌سوکت‌های بلادرنگ و زیرساخت‌های ابری مقیاس‌پذیر.',
    stats: [
      { labelEn: 'Availability', labelFa: 'پایداری سرور', val: '99.99%' },
      { labelEn: 'Throughput', labelFa: 'پاسخ‌دهی', val: '<15ms' },
      { labelEn: 'Security', labelFa: 'امنیت ابری', val: 'Hardened' },
    ],
    skillsEn: ['Distributed Systems', 'PostgreSQL & Redis', 'Node.js & Go', 'Docker & K8s'],
    skillsFa: ['سیستم‌های توزیع‌شده', 'پایگاه‌داده و کش', 'نودجی‌اس و گو', 'داکر و کلود'],
    coord: { x: 80, y: 26 },
    connectsWith: ['rouhollah', 'danial'],
  },
  {
    id: 'arash',
    code: 'JRK-WEB-03',
    nameEn: 'Arash',
    nameFa: 'آرش',
    roleEn: 'Senior Fullstack & Microservices Architect Engineer',
    roleFa: 'مهندس ارشد فول‌استک و معماری مایکروسرویس‌های وب',
    badgeEn: 'SPECIALIST',
    badgeFa: 'متخصص فنی',
    isFounder: false,
    department: 'web-dev',
    image: '/assets/images/team/arash.jpg',
    bioEn: 'Architecting scalable enterprise platforms, API gateways, and real-time state synchronization.',
    bioFa: 'معماری پلتفرم‌های مقیاس‌پذیر سازمانی، گذرگاه‌های ارتباطی و همگام‌سازی بلادرنگ داده‌ها.',
    stats: [
      { labelEn: 'Scalability', labelFa: 'مقیاس‌پذیری', val: 'High' },
      { labelEn: 'Experience', labelFa: 'سابقه کار', val: '7+ Yrs' },
      { labelEn: 'Code Quality', labelFa: 'استاندارد کد', val: 'Clean' },
    ],
    skillsEn: ['TypeScript', 'GraphQL', 'Microservices', 'Kubernetes'],
    skillsFa: ['تایپ‌اسکریپت', 'گراف‌کیوال', 'مایکروسرویس', 'کوبرنتیز'],
    coord: { x: 45, y: 28 },
    connectsWith: ['danial', 'maryam'],
  },
  {
    id: 'sepideh',
    code: 'JRK-WEB-04',
    nameEn: 'Sepideh',
    nameFa: 'سپیده',
    roleEn: 'Creative Technologist & Interactive Design Systems Specialist',
    roleFa: 'متخصص تکنولوژی خلاق و دیزاین سیستم‌های تعاملی',
    badgeEn: 'SPECIALIST',
    badgeFa: 'متخصص فنی',
    isFounder: false,
    department: 'web-dev',
    image: '/assets/images/team/sepideh.jpg',
    bioEn: 'Bridging avant-garde interaction design with rock-solid component architectures and accessibility.',
    bioFa: 'پیوند دیزاین تعاملی آوانگارد با معماری استوار کامپوننت‌ها و دسترسی‌پذیری وب.',
    stats: [
      { labelEn: 'Design Ops', labelFa: 'دیزاین آپس', val: 'Systemic' },
      { labelEn: 'Accessibility', labelFa: 'دسترسی‌پذیری', val: 'WCAG AAA' },
      { labelEn: 'Precision', labelFa: 'دقت اجرا', val: 'Pixel' },
    ],
    skillsEn: ['Design Systems', 'Micro-Interactions', 'CSS Architecture', 'React'],
    skillsFa: ['دیزاین سیستم', 'میکرواینتراکشن', 'معماری استایل', 'ری‌اکت'],
    coord: { x: 30, y: 32 },
    connectsWith: ['danial', 'sina'],
  },
  {
    id: 'farbod',
    code: 'JRK-WEB-05',
    nameEn: 'Farbod',
    nameFa: 'فربد',
    roleEn: 'Web Performance Optimization & Real-Time Data Architect',
    roleFa: 'متخصص بهینه‌سازی پرفورمنس وب و جریان‌های بلادرنگ داده',
    badgeEn: 'SPECIALIST',
    badgeFa: 'متخصص فنی',
    isFounder: false,
    department: 'web-dev',
    image: '/assets/images/team/farbod.jpg',
    bioEn: 'Obsessed with sub-millisecond render pipelines, tree-shaking, and high-frequency data streaming.',
    bioFa: 'بهینه‌سازی حداکثری سرعت بارگذاری، پایپ‌لاین‌های رندر سبک و ارتباطات پرسرعت داده.',
    stats: [
      { labelEn: 'Lighthouse', labelFa: 'امتیاز سرعت', val: '100/100' },
      { labelEn: 'Load Time', labelFa: 'زمان لود', val: '<0.4s' },
      { labelEn: 'Optimizations', labelFa: 'بهینه‌سازی', val: 'Native' },
    ],
    skillsEn: ['Web Performance', 'SSR & SSG', 'Bundling', 'HTTP/3'],
    skillsFa: ['پرفورمنس وب', 'رندرسرور', 'بهینه‌سازی باندل', 'ارتباطات مدرن'],
    coord: { x: 60, y: 30 },
    connectsWith: ['rouhollah', 'maryam'],
  },
  {
    id: 'parisa',
    code: 'JRK-WEB-06',
    nameEn: 'Parisa',
    nameFa: 'پریسا',
    roleEn: 'Quality Assurance & Automated Testing Infrastructure Lead',
    roleFa: 'سرپرست تضمین کیفیت نرم‌افزار و زیرساخت تست خودکار',
    badgeEn: 'SPECIALIST',
    badgeFa: 'متخصص فنی',
    isFounder: false,
    department: 'web-dev',
    image: '/assets/images/team/parisa.jpg',
    bioEn: 'Ensuring zero-regression deployment pipelines through end-to-end automated testing suites.',
    bioFa: 'تضمین پایداری بدون نقص و استقرار مداوم با تست‌های جامع و خودکار سرتاسری.',
    stats: [
      { labelEn: 'Test Coverage', labelFa: 'پوشش تست', val: '98%' },
      { labelEn: 'Reliability', labelFa: 'پایداری', val: 'High' },
      { labelEn: 'CI/CD', labelFa: 'استقرار خودکار', val: 'Automated' },
    ],
    skillsEn: ['Playwright', 'Jest & Vitest', 'CI/CD Pipelines', 'Integration Tests'],
    skillsFa: ['پلی‌رایت', 'تست‌های اتوماتیک', 'پایپ‌لاین CI/CD', 'تضمین کیفیت'],
    coord: { x: 75, y: 35 },
    connectsWith: ['danial', 'arash'],
  },

  // 3. SEO & ANALYTICS
  {
    id: 'kamran',
    code: 'JRK-SEO-01',
    nameEn: 'Kamran',
    nameFa: 'کامران',
    roleEn: 'Senior Technical SEO Strategist',
    roleFa: 'استراتژیست ارشد سئو تکنیکال',
    badgeEn: 'SPECIALIST',
    badgeFa: 'متخصص سئو',
    isFounder: false,
    department: 'seo-analytics',
    image: '/assets/images/team/kamran.jpg',
    bioEn: 'Auditing deep technical website architectures, Core Web Vitals, organic crawl budgets, and search visibility.',
    bioFa: 'تحلیل عمیق معماری سئوی تکنیکال، بهینه‌سازی سرعت هسته وب (CWV)، بودجه خزش و دیده‌شدن ارگانیک در موتورهای جستجو.',
    stats: [
      { labelEn: 'Organic Growth', labelFa: 'رشد ارگانیک', val: '+240%' },
      { labelEn: 'Core Vitals', labelFa: 'شاخص CWV', val: '98/100' },
      { labelEn: 'Index Ratio', labelFa: 'نرخ ایندکس', val: '100%' },
    ],
    skillsEn: ['Technical SEO', 'Schema & Semantics', 'Crawl Optimization', 'SERP Domination'],
    skillsFa: ['سئو تکنیکال', 'اسکیما و داده معنایی', 'بهینه‌سازی بودجه خزش', 'تحلیل رقبا'],
    coord: { x: 18, y: 64 },
    connectsWith: ['danial', 'negar'],
  },
  {
    id: 'negar',
    code: 'JRK-SEO-02',
    nameEn: 'Negar',
    nameFa: 'نگار',
    roleEn: 'Data Analyst & Conversion Specialist',
    roleFa: 'متخصص تحلیل داده و رفتار کاربر',
    badgeEn: 'SPECIALIST',
    badgeFa: 'تحلیل داده',
    isFounder: false,
    department: 'seo-analytics',
    image: '/assets/images/team/elham.jpg',
    bioEn: 'Synthesizing quantitative telemetry, session heatmaps, attribution funnels, and data-driven growth experiments.',
    bioFa: 'تحلیل رفتار تعاملی کاربران، هیت‌مپ‌های صفحات، کانال‌های ورودی و بهینه‌سازی مداوم نرخ تبدیل با رویکرد داده‌محور.',
    stats: [
      { labelEn: 'Attribution', labelFa: 'دقت تحلیل', val: 'Precise' },
      { labelEn: 'A/B Testing', labelFa: 'تست‌های A/B', val: '50+ Runs' },
      { labelEn: 'Conversion', labelFa: 'افزایش لید', val: '+35%' },
    ],
    skillsEn: ['Product Analytics', 'GA4 & BigQuery', 'CRO Strategies', 'User Funnels'],
    skillsFa: ['تحلیل محصول', 'گوگل آنالیتیکس ۴', 'بهینه‌سازی نرخ تبدیل', 'قیف‌های تبدیل'],
    coord: { x: 30, y: 78 },
    connectsWith: ['kamran', 'mahsa'],
  },

  // 4. BRANDING & IDENTITY
  {
    id: 'parsa',
    code: 'JRK-BRD-01',
    nameEn: 'Parsa',
    nameFa: 'پارسا',
    roleEn: 'Senior Visual Identity & Type Designer',
    roleFa: 'طراح ارشد هویت بصری و تایپوگرافی',
    badgeEn: 'SPECIALIST',
    badgeFa: 'دیزاین برند',
    isFounder: false,
    department: 'branding-identity',
    image: '/assets/images/team/sina.jpg',
    bioEn: 'Designing memorable visual emblems, bespoke typeface ligatures, color psychology systems, and guidelines.',
    bioFa: 'خلق نشان‌های بصری ماندگار، تایپ‌فیس‌های سفارشی، هارمونی‌های رنگی روان‌شناختی و کتابچه‌های جامع هویت برند.',
    stats: [
      { labelEn: 'Brand Books', labelFa: 'هویت برند', val: '30+ Created' },
      { labelEn: 'Type Ligatures', labelFa: 'تایپ‌دیزاین', val: 'Custom' },
      { labelEn: 'Consistency', labelFa: 'انسجام بصری', val: 'Flawless' },
    ],
    skillsEn: ['Custom Typography', 'Brand Guidelines', 'Logo Design', 'Print & Editorial'],
    skillsFa: ['تایپوگرافی سفارشی', 'کتابچه هویت برند', 'طراحی لوگو و نماد', 'چاپ و بسته‌بندی'],
    coord: { x: 70, y: 72 },
    connectsWith: ['sina', 'yasaman'],
  },
  {
    id: 'yasaman',
    code: 'JRK-BRD-02',
    nameEn: 'Yasaman',
    nameFa: 'یاسمن',
    roleEn: 'Verbal Identity & Brand Strategist',
    roleFa: 'استراتژیست هویت کلامی و روایت برند',
    badgeEn: 'SPECIALIST',
    badgeFa: 'استراتژی برند',
    isFounder: false,
    department: 'branding-identity',
    image: '/assets/images/team/sara.jpg',
    bioEn: 'Defining brand tone-of-voice, architectural naming matrix, bespoke slogans, and resonant cultural messaging.',
    bioFa: 'تدوین لحن کلامی برند (Tone of Voice)، نام‌گذاری سیستماتیک محصولات و خدمات، شعارها و روایت‌گری اثربخش تجاری.',
    stats: [
      { labelEn: 'Naming Matrix', labelFa: 'نام‌گذاری', val: 'Systemic' },
      { labelEn: 'Voice Depth', labelFa: 'عمق کلامی', val: 'Authentic' },
      { labelEn: 'Brand Trust', labelFa: 'شاخص تمایز', val: 'High' },
    ],
    skillsEn: ['Brand Naming', 'Tone of Voice', 'Verbal Architecture', 'Copy Direction'],
    skillsFa: ['نام‌گذاری تجاری', 'لحن کلام برند', 'معماری کلامی', 'روایت برند'],
    coord: { x: 84, y: 64 },
    connectsWith: ['parsa', 'sina'],
  },

  // 5. CREATIVE STUDIO
  {
    id: 'nima',
    code: 'JRK-CRT-01',
    nameEn: 'Nima',
    nameFa: 'نیما',
    roleEn: 'Motion Director & Sound Designer',
    roleFa: 'کارگردان موشن و هویت صوتی',
    badgeEn: 'SPECIALIST',
    badgeFa: 'موشن و صدا',
    isFounder: false,
    department: 'creative-studio',
    image: '/assets/images/team/nima.jpg',
    bioEn: 'Composing organic generative audio signatures, kinetic title animations, and micro-haptic auditory feedback.',
    bioFa: 'پیوند زدن انیمیشن‌های کینتیک با فضاهای صوتی ارگانیک، طراحی صدای تعاملی و امضای شنیداری پروژه‌های استودیو.',
    stats: [
      { labelEn: 'Audio Engine', labelFa: 'طراحی صدا', val: '48kHz / 24b' },
      { labelEn: 'Kinetic Motion', labelFa: 'حرکت کینتیک', val: 'Dynamic' },
      { labelEn: 'Sonic Score', labelFa: 'امتیاز هنری', val: '98%' },
    ],
    skillsEn: ['Motion Graphics', 'Sound Design', 'After Effects', 'Ableton & Synths'],
    skillsFa: ['موشن گرافیک', 'طراحی صدا', 'افترافکت و انیمیشن', 'سینتی‌سایزر آنالوگ'],
    coord: { x: 38, y: 72 },
    connectsWith: ['sina', 'sara'],
  },
  {
    id: 'sara',
    code: 'JRK-CRT-02',
    nameEn: 'Sara',
    nameFa: 'سارا',
    roleEn: '3D & Spatial Concept Artist',
    roleFa: 'آرتیست سه‌بعدی و فضاسازی تجربی',
    badgeEn: 'SPECIALIST',
    badgeFa: 'فضاسازی سه‌بعدی',
    isFounder: false,
    department: 'creative-studio',
    image: '/assets/images/team/sara.jpg',
    bioEn: 'Crafting surreal procedural environments, physical material shaders, lighting physics, and architectural visual concepts.',
    bioFa: 'طراحی فضاهای ایمرسیو و سورئال، شیدرهای فیزیکی نور و ماده، رندرهای مفهومی و دنیای سه‌بعدی پروژه‌ها.',
    stats: [
      { labelEn: 'Lighting Ray', labelFa: 'کیفیت رندر', val: 'PBR 4K' },
      { labelEn: 'Spatial Flow', labelFa: 'روانی فضا', val: 'Seamless' },
      { labelEn: '3D Worlds', labelFa: 'دنیاهای ۳D', val: '20+ Built' },
    ],
    skillsEn: ['Blender & Houdini', 'PBR Materials', 'Spatial Composition', 'Substance Painter'],
    skillsFa: ['بلندر و هودینی', 'متریال‌های فیزیکی', 'ترکیب‌بندی فضایی', 'تکسچرینگ واقع‌گرایانه'],
    coord: { x: 50, y: 82 },
    connectsWith: ['nima', 'rouhollah'],
  },

  // 6. DIGITAL MARKETING & GROWTH
  {
    id: 'mahsa',
    code: 'JRK-MKT-01',
    nameEn: 'Mahsa',
    nameFa: 'مهسا',
    roleEn: 'Growth & Performance Marketing Lead',
    roleFa: 'مدیر بازاریابی عملکردمحور و قیف رشد',
    badgeEn: 'SPECIALIST',
    badgeFa: 'مارکتینگ',
    isFounder: false,
    department: 'digital-marketing',
    image: '/assets/images/team/mahsa.jpg',
    bioEn: 'Architecting performance-driven media campaigns, automated conversion funnels, and data-backed customer acquisition.',
    bioFa: 'طراحی کمپین‌های تبلیغاتی نتیجه‌گرا، اتوماسیون قیف‌های جذب و تبدیل مخاطب، و بهینه‌سازی هوشمند بودجه‌های بازاریابی.',
    stats: [
      { labelEn: 'ROAS', labelFa: 'بازگشت سرمایه', val: '4.8x Avg' },
      { labelEn: 'Acquisition', labelFa: 'جذب کاربر', val: 'Scalable' },
      { labelEn: 'Campaigns', labelFa: 'کمپین‌ها', val: '120+' },
    ],
    skillsEn: ['Performance Ads', 'Conversion Funnels', 'Marketing Automation', 'Growth Loops'],
    skillsFa: ['کمپین‌های عملکردمحور', 'قیف‌های تبدیل', 'اتوماسیون مارکتینگ', 'حلقه‌های رشد'],
    coord: { x: 14, y: 48 },
    connectsWith: ['kamran', 'negar', 'abdollah'],
  },

  // 7. GAME STUDIO & INTERACTIVE
  {
    id: 'behdad',
    code: 'JRK-GAM-01',
    nameEn: 'Behdad',
    nameFa: 'بهداد',
    roleEn: 'Game Systems & Mechanics Designer',
    roleFa: 'طراح مکانیک بازی و گیمیفیکیشن',
    badgeEn: 'SPECIALIST',
    badgeFa: 'بازی و تعامل',
    isFounder: false,
    department: 'game-interactive',
    image: '/assets/images/team/kamran.jpg',
    bioEn: 'Prototyping dynamic gameplay loops, physics-based puzzles, interactive web mechanics, and engaging gamified experiences.',
    bioFa: 'طراحی حلقه‌های گیم‌پلی پویا، مکانیک‌های فیزیکی تعاملی در وب، بازی‌وارسازی سیستم‌ها و تجارب سرگرم‌کننده دیجیتال.',
    stats: [
      { labelEn: 'Play Mechanics', labelFa: 'مکانیک بازی', val: 'Intuitive' },
      { labelEn: 'Physics Engine', labelFa: 'موتور فیزیک', val: 'Rapier/Cannon' },
      { labelEn: 'Engagement', labelFa: 'درگیری کاربر', val: '+75%' },
    ],
    skillsEn: ['Game Mechanics', 'Three.js Physics', 'Gamification', 'Level Design'],
    skillsFa: ['مکانیک‌های بازی', 'فیزیک در وب', 'گیمیفیکیشن تعاملی', 'طراحی مراحل'],
    coord: { x: 86, y: 46 },
    connectsWith: ['rouhollah', 'sara'],
  },

  // 8. ACADEMY & LEARNING HUB
  {
    id: 'elham',
    code: 'JRK-ACD-01',
    nameEn: 'Elham',
    nameFa: 'الهام',
    roleEn: 'Academy Lead & Creative Researcher',
    roleFa: 'مدیر آکادمی و پژوهشگر خلاقیت',
    badgeEn: 'SPECIALIST',
    badgeFa: 'آموزش و آکادمی',
    isFounder: false,
    department: 'academy-hub',
    image: '/assets/images/team/elham.jpg',
    bioEn: 'Curating advanced professional workshops, creative mentorship curricula, and synthesizing cultural design research.',
    bioFa: 'برنامه‌ریزی کارگاه‌های تخصصی پیشرفته، تدوین سرفصل‌های منتورشیپ خلاق، و پژوهش پیرامون تقاطع هنر، فناوری و انسان.',
    stats: [
      { labelEn: 'Workshops', labelFa: 'کارگاه‌ها', val: '45+ Held' },
      { labelEn: 'Students', labelFa: 'دانش‌آموختگان', val: '1,200+' },
      { labelEn: 'Curriculum', labelFa: 'سرفصل‌ها', val: 'Practical' },
    ],
    skillsEn: ['Educational Design', 'Mentorship', 'Design Research', 'Community Hub'],
    skillsFa: ['طراحی دوره‌های آموزشی', 'منتورشیپ تخصصی', 'پژوهش دیزاین', 'توسعه جامعه متخصصان'],
    coord: { x: 50, y: 20 },
    connectsWith: ['abdollah', 'rouhollah', 'sina'],
  },
];
